apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cd-listener
spec:
  # Set serviceAccountName
  serviceAccountName: pipeline
  # Reference TriggerBinding and TriggerTemplate
  triggers:
    - bindings:
      - ref: cd-binding 
      template:
        ref: cd-template
